# Generated by Django 4.2.3 on 2023-08-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='contact_num',
            new_name='phone_num',
        ),
    ]
